/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.arduinoaula1;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.DefaultXYDataset;
import org.jfree.data.xy.XYDataset;

/**
 *
 * @author thiago
 */
public class NewJFrame extends javax.swing.JFrame {
    
    static List<Double> leituras = new ArrayList<>();
    static List<Double> listaTemperatureValues = new ArrayList<>();
    static List<Double> listLuminosidade = new ArrayList<>();
//    static JFrame frame = new JFrame("Charts");
    static double i = 0;
    static JFreeChart chart;
    static ChartPanel cp;
    static XYDataset ds;
    
    private Javino jBridge = new Javino("/anaconda3/envs/python2710/bin");
    private String porta = "/dev/cu.usbmodem1421";

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        cp = new ChartPanel(chart);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        panel1 = new java.awt.Panel();
        button1 = new java.awt.Button();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        button1.setLabel("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        UIUpdater t = new UIUpdater();
        t.start();
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    private static XYDataset createDataset() {

        listaTemperatureValues.add(generateRandomicValue());
        listLuminosidade.add(generateRandomicValue());
        leituras.add(i++);

        DefaultXYDataset ds = new DefaultXYDataset();
        double[] arrayLeituras = new double[leituras.size()];
        for (int i = 0; i < leituras.size(); i++) {
            arrayLeituras[i] = leituras.get(i);
        }

        double[] arrayTemperaturas = new double[listaTemperatureValues.size()];
        for (int i = 0; i < listaTemperatureValues.size(); i++) {
            arrayTemperaturas[i] = listaTemperatureValues.get(i);
        }

        double[] arrayLuminosidade = new double[listLuminosidade.size()];
        for (int i = 0; i < listLuminosidade.size(); i++) {
            arrayLuminosidade[i] = listLuminosidade.get(i);
        }

        double[][] serieTemperatura = {arrayLeituras, arrayTemperaturas};

        double[][] serieLuminosidade = {arrayLeituras, arrayLuminosidade};

        ds.addSeries("Temperaturas", serieTemperatura);
        ds.addSeries("Luminosidade", serieLuminosidade);

        return ds;
    }

    private static double generateRandomicValue() {
        double value = Math.random();
        return value;
    }

    class UIUpdater extends Thread {

        @Override
        public void run() {
            while (true) {
                try {
//                    frame.setSize(600, 400);
//                    jFrame1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//                    frame.setVisible(true);

                    ds = createDataset();
                    chart = ChartFactory.createXYLineChart("Aula 1",
                            "x", "y", ds, PlotOrientation.VERTICAL, true, true,
                            false);
                    cp.setChart(chart);
                    cp.setSize(400, 300);
                    cp.setDomainZoomable(true);
//                    cp.repaint();

//                    cp.setPreferredSize(new java.awt.Dimension(500, 270));

                    panel1.add(cp, BorderLayout.CENTER);
                    panel1.repaint();
                    panel1.setVisible(true);

                } catch (Exception e) {
                    System.out.println("Error: " + e);
                } finally {
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                        ex.printStackTrace();
                    }
                }
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JFrame jFrame1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
